ARG baseImageTag
ARG baseImageUri
FROM ${baseImageUri}:${baseImageTag}

ARG version
ARG mavenArtifactBaseUrl
ARG wildfly_home=/opt/jboss/wildfly
ARG wildfly_user=jboss
ARG context_group_name=bpm
ARG context_name=businessprocesses
ARG framework_version=17.101.6
ARG eventstore_version=17.101.5

ADD ${mavenArtifactBaseUrl}/uk/gov/moj/cpp/${context_group_name}/${context_name}-service/${version}/${context_name}-service-${version}.war ${wildfly_home}/standalone/deployments/
USER root
RUN chown -R ${wildfly_user}:${wildfly_user} ${wildfly_home}/standalone/deployments/ && chmod -R 700 ${wildfly_home}/standalone/deployments/

# liquibase jars & config
RUN mkdir /tmp/liquibase
ADD ${mavenArtifactBaseUrl}/uk/gov/moj/cpp/bpm/businessprocesses-viewstore-liquibase/${version}/businessprocesses-viewstore-liquibase-${version}.jar /tmp/liquibase/businessprocesses-viewstore-liquibase.jar
ADD ${mavenArtifactBaseUrl}/uk/gov/justice/event-store/event-repository-liquibase/${eventstore_version}/event-repository-liquibase-${eventstore_version}.jar  /tmp/liquibase/event-repository-liquibase.jar
ADD ${mavenArtifactBaseUrl}/uk/gov/justice/event-store/aggregate-snapshot-repository-liquibase/${eventstore_version}/aggregate-snapshot-repository-liquibase-${eventstore_version}.jar  /tmp/liquibase/aggregate-snapshot-repository-liquibase.jar
ADD ${mavenArtifactBaseUrl}/uk/gov/justice/event-store/event-buffer-liquibase/${eventstore_version}/event-buffer-liquibase-${eventstore_version}.jar  /tmp/liquibase/event-buffer-liquibase.jar
ADD ${mavenArtifactBaseUrl}/uk/gov/justice/event-store/event-tracking-liquibase/${eventstore_version}/event-tracking-liquibase-${eventstore_version}.jar  /tmp/liquibase/event-tracking-liquibase.jar
ADD ${mavenArtifactBaseUrl}/uk/gov/justice/services/framework-system-liquibase/${framework_version}/framework-system-liquibase-${framework_version}.jar  /tmp/liquibase/framework-system-liquibase.jar
RUN chown -R ${wildfly_user}:${wildfly_user} /tmp/liquibase
RUN chmod -R 755 /tmp/liquibase
COPY scripts/liquibase.sh /tmp/liquibase/liquibase.sh
RUN chown ${wildfly_user}:${wildfly_user} /tmp/liquibase/liquibase.sh && chmod 755 /tmp/liquibase/liquibase.sh

RUN mkdir /opt/cpp-tools
ADD ${mavenArtifactBaseUrl}/uk/gov/justice/services/framework-jmx-command-client/${framework_version}/framework-jmx-command-client-${framework_version}.jar /opt/cpp-tools/framework-jmx-command-client.jar
RUN chown ${wildfly_user}:${wildfly_user} /opt/cpp-tools/framework-jmx-command-client.jar && chmod 755 /opt/cpp-tools/framework-jmx-command-client.jar

USER ${wildfly_user}
LABEL base_image ${baseImageTag}